### ISSUE TITLE
Add Leipzig to new opentechschool logo to avoid conflicts with OTS

### ISSUE THREAD

**Issue by normade** [OpenTechSchool-Leipzig/hackolaus#17]

**Comment by Twissi** [comment]
Maybe just the Open Tech School Leipzig text with the HvD Pluto font.
https://www.opentechschool.org/handbooks/styles.html

**Comment by Twissi** [comment]
or is this a new official logo i don't know about?

**Comment by normade** [comment]
I think @danmcatee just wanted to give us a new logo design? I appreciate that but we would need to align with the OTS or ask them to use an own design?

**Comment by Twissi** [comment]
yeah I love the new design, it would probably work great with the webdesign relaunch :) I will talk with the Berlin organisers about it. For now we should just use white text font.

**Comment by normade** [comment]
Yes, I agree. Let's use the the text only for now. Could we also list the partners one below the other on mobile devices if this doesn't cause big work?

**Comment by normade** [comment]
The mobile layout for company and partner logos will be done with #26.
