### ISSUE TITLE
Add a hover state for the candy up button

### ISSUE THREAD

**Issue by markusphil** [OpenTechSchool-Leipzig/hackolaus#30]
It should feel a bit more exciting!

**Comment by normade** [comment]
Candy glitter 😍 ?

**Comment by markusphil** [comment]
https://codepen.io/simeydotme/pen/jgcvi

something like this? Maybe we could use some snowflakes instead :P
But I think we'd have to use JS to add the glitter...

Or we try to adapt this for the buttons: https://pajasevi.github.io/CSSnowflakes/

**Comment by normade** [comment]
@markusphil great 🌟 I like the colored ones on the heading in codepen. But I am fine with snowflakes too :-)

**Comment by Twissi** [comment]
I also like the first one better

**Comment by Twissi** [comment]
Gave it a shot with a simple svg animation. Not quite happy with it. I think Elli would do a better job on this. https://github.com/OpenTechSchool-Leipzig/hackolaus/tree/button-animation

**Comment by Twissi** [comment]
Maybe it looks better if we add 100 more stars to the svg 🤔

**Comment by markusphil** [comment]
I just tried to build a snowflake-animation thingy: https://codesandbox.io/embed/clever-mccarthy-wdm2j
Maybe we can use it somewhere =)

**Comment by Twissi** [comment]
@markusphil thanks for playing around with it! I think we are going with the crazy snowflake for now without js. 🤣 🍭

**Comment by markusphil** [comment]
@Twissi Haha comparing to that exploding colors my snowflakes a pretty boring! 🤣 I like it! 😊
