### ISSUE TITLE
Add venue closing time

### ISSUE THREAD

**Issue by Twissi** [OpenTechSchool-Leipzig/hackolaus#33]
Add closing time or remove faq qq

```
Will the venue be open overnight?
No, the venue will close at ___ .
```

**Comment by normade** [comment]
@Twissi it will be open all night (theoretically)

**Comment by Twissi** [comment]
Not sure we need this faq question

Does this add any value? I am fine with removing the question. `Yes. The venue will remain open for hackathon participants though the weekend to support the event`

**Comment by normade** [comment]
@Twissi yes, I have no feelings here at all. Add this answer (must it be `through`?) or remove the whole thing.

**Comment by normade** [comment]
Maybe we should also remove "food and drinks" etc. for now, as I am not sure what we will be able to afford.
