### ISSUE TITLE
Add Sponsor Info Page

### ISSUE THREAD

**Issue by markusphil** [OpenTechSchool-Leipzig/hackolaus#44]
Adding the sponsor-infos to a separate page might help attract some companies 🤔

**Comment by normade** [comment]
Yes true, but no real content is available unfortunately.

**Comment by markusphil** [comment]
Is the sponsorship doc you posted in Slack not final yet? I thought we might just copy it.

**Comment by normade** [comment]
No unfortunately not, it's more or less outdated if I am not wrong, as they already did changes or during meetings with potential sponsors things changed ... but I will ask if it is like this and what we could communicate.
